// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbDz22wTkv7j4Uxsa7ceWmWfR2Hyw9i_Q',
    appId: '1:318243336496:web:44044e02c578ddedd018f5',
    messagingSenderId: '318243336496',
    projectId: 'fingerprint-c7514',
    authDomain: 'fingerprint-c7514.firebaseapp.com',
    storageBucket: 'fingerprint-c7514.firebasestorage.app',
    measurementId: 'G-6MJ17VR88Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZqpOfOBB0wjZkec5f8MLnTKlus0Y9V20',
    appId: '1:318243336496:android:31d46ba1f46a7fe9d018f5',
    messagingSenderId: '318243336496',
    projectId: 'fingerprint-c7514',
    storageBucket: 'fingerprint-c7514.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgxXGQxizFraHyOARK1LOnZQy3JUXb6_Y',
    appId: '1:318243336496:ios:2bcdfe7cc9c54048d018f5',
    messagingSenderId: '318243336496',
    projectId: 'fingerprint-c7514',
    storageBucket: 'fingerprint-c7514.firebasestorage.app',
    iosClientId: '318243336496-evbo61akhqi4dfc6o38t33a20vgsu8up.apps.googleusercontent.com',
    iosBundleId: 'com.example.rasdApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgxXGQxizFraHyOARK1LOnZQy3JUXb6_Y',
    appId: '1:318243336496:ios:2bcdfe7cc9c54048d018f5',
    messagingSenderId: '318243336496',
    projectId: 'fingerprint-c7514',
    storageBucket: 'fingerprint-c7514.firebasestorage.app',
    iosClientId: '318243336496-evbo61akhqi4dfc6o38t33a20vgsu8up.apps.googleusercontent.com',
    iosBundleId: 'com.example.rasdApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbDz22wTkv7j4Uxsa7ceWmWfR2Hyw9i_Q',
    appId: '1:318243336496:web:b8d1b2f47baffef9d018f5',
    messagingSenderId: '318243336496',
    projectId: 'fingerprint-c7514',
    authDomain: 'fingerprint-c7514.firebaseapp.com',
    storageBucket: 'fingerprint-c7514.firebasestorage.app',
    measurementId: 'G-1B29Y281EL',
  );
}
